# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.13.106:3306/house_collection_test?characterEncoding=UTF-8
    username: setest
    password: HnshengenSeDb@3108
    filters: wall,mergeStat
