server:
  port: 8094
  tomcat:
     max-http-header-size: 10240

housecollection:
  swagger-open: true                #\u662F\u5426\u5F00\u542Fswagger (true/false)
  kaptcha-open: false               #\u662F\u5426\u5F00\u542F\u767B\u5F55\u65F6\u9A8C\u8BC1\u7801 (true/false)
  spring-session-open: false        #\u662F\u5426\u5F00\u542Fspring session,\u5982\u679C\u662F\u591A\u673A\u73AF\u5883\u9700\u8981\u5F00\u542F(true/false)
  session-invalidate-time: 7200     #session\u5931\u6548\u65F6\u95F4(\u53EA\u5728\u5355\u673A\u73AF\u5883\u4E0B\u751F\u6548\uFF0C\u591A\u673A\u73AF\u5883\u5728SpringSessionConfig\u7C7B\u4E2D\u914D\u7F6E) \u5355\u4F4D\uFF1A\u79D2
  session-validation-interval: 900  #\u591A\u4E45\u68C0\u6D4B\u4E00\u6B21\u5931\u6548\u7684session(\u53EA\u5728\u5355\u673A\u73AF\u5883\u4E0B\u751F\u6548) \u5355\u4F4D\uFF1A\u79D2

beetl:
  resource-auto-check: true         #\u70ED\u52A0\u8F7Dbeetl\u6A21\u677F\uFF0C\u5F00\u53D1\u65F6\u5019\u7528

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  dubbo:
    application:
      name: house-web
    registry:
      protocol: zookeeper
      address: localhost:2181
    base-package: com.hnshengen.housecollection
    protocol:
      name: dubbo
    consumer:
      timeout: 10000
      check: false

mybatis-plus:
  typeAliasesPackage: com.se.jizi.modular.*.model
  mapper-locations: classpath:com/se/jizi/modular/**/mapping/*.xml

log:
  path: jizi-logs

wechat:
  myAppId: wx4622d866de87ea14
  myAppSecret: acd8663894cdaf6bcbd97e0ac5dce640